// src/storage/storage.service.js
const { createClient } = require('@supabase/supabase-js');
const { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY } = require('../config/env');

const bucket = 'numor-invoice-pdf-storage';

const supabase = createClient(
  SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY,
  {
    auth: { autoRefreshToken: false, persistSession: false }
  }
);

async function upload(key, buffer, contentType) {
  const { error } = await supabase.storage
    .from(bucket)
    .upload(key, buffer, {
      contentType: contentType || 'application/pdf',
      upsert: true
    });

  if (error) throw error;
  return key;
}

// Pulls a stored file back as a Buffer. Needed when an email has to be sent for
// an invoice whose PDF was generated by an earlier job - the buffer is long gone,
// but the file is still in the bucket.
async function download(key) {
  const { data, error } = await supabase.storage.from(bucket).download(key);

  if (error) throw error;
  return Buffer.from(await data.arrayBuffer());
}

async function getSignedUrl(key) {
  const { data, error } = await supabase.storage
    .from(bucket)
    .createSignedUrl(key, 900, {
      download: true
    });

  if (error) throw error;
  return data.signedUrl;
}

async function getSignedUrls(keys) {
  const { data, error } = await supabase.storage
    .from(bucket)
    .createSignedUrls(keys, 900, {
      download: true
    });

  if (error) throw error;

  return data.reduce((acc, item) => {
    acc[item.path] = item.signedUrl;
    return acc;
  }, {});
}

async function remove(key) {
  const { data, error } = await supabase.storage
    .from(bucket)
    .remove([key]); // must be array

  if (error) throw error;

  return data;
}

// Batched delete for bulk teardown (see scripts/delete-organization.js).
// Supabase caps the number of paths per remove() call, so chunk it rather
// than firing one request per file.
const REMOVE_CHUNK_SIZE = 100;

async function removeMany(keys) {
  const unique = [...new Set(keys.filter(Boolean))];
  let removed = 0;

  for (let i = 0; i < unique.length; i += REMOVE_CHUNK_SIZE) {
    const chunk = unique.slice(i, i + REMOVE_CHUNK_SIZE);
    const { data, error } = await supabase.storage.from(bucket).remove(chunk);

    if (error) throw error;
    removed += data?.length ?? 0;
  }

  return { requested: unique.length, removed };
}

module.exports = {
  upload,
  download,
  getSignedUrl,
  getSignedUrls,
  remove,
  removeMany
};
